[workspace]
resolver = "2"

members = [
    "api",
    "api/openapi-spec-generator",
    "api/types",
    "aptos-move/aptos-gas",
    "aptos-move/aptos-resource-viewer",
    "aptos-move/aptos-sdk-builder",
    "aptos-move/aptos-transaction-benchmarks",
    "aptos-move/aptos-transactional-test-harness",
    "aptos-move/aptos-validator-interface",
    "aptos-move/aptos-vm",
    "aptos-move/e2e-move-tests",
    "aptos-move/e2e-tests",
    "aptos-move/e2e-testsuite",
    "aptos-move/framework",
    "aptos-move/framework/cached-packages",
    "aptos-move/genesis-viewer",
    "aptos-move/move-deps",
    "aptos-move/move-examples",
    "aptos-move/mvhashmap",
    "aptos-move/parallel-executor",
    "aptos-move/transaction-replay",
    "aptos-move/vm-genesis",
    "aptos-move/writeset-transaction-generator",
    "aptos-node",
    "config",
    "config/global-constants",
    "config/management",
    "config/management/operational",
    "config/seed-peer-generator",
    "consensus",
    "consensus/consensus-types",
    "consensus/safety-rules",
    "crates/aptos",
    "crates/aptos-bitvec",
    "crates/aptos-compression",
    "crates/aptos-crypto",
    "crates/aptos-crypto-derive",
    "crates/aptos-faucet",
    "crates/aptos-faucet-cli",
    "crates/aptos-genesis",
    "crates/aptos-id-generator",
    "crates/aptos-infallible",
    "crates/aptos-keygen",
    "crates/aptos-log-derive",
    "crates/aptos-logger",
    "crates/aptos-metrics-core",
    "crates/aptos-openapi",
    "crates/aptos-proptest-helpers",
    "crates/aptos-rate-limiter",
    "crates/aptos-rest-client",
    "crates/aptos-retrier",
    "crates/aptos-rosetta",
    "crates/aptos-rosetta-cli",
    "crates/aptos-telemetry",
    "crates/aptos-temppath",
    "crates/aptos-time-service",
    "crates/bounded-executor",
    "crates/channel",
    "crates/crash-handler",
    "crates/fallible",
    "crates/inspection-service",
    "crates/num-variants",
    "crates/proxy",
    "crates/short-hex-str",
    "crates/transaction-emitter",
    "crates/transaction-emitter-lib",
    "ecosystem/indexer",
    "ecosystem/node-checker",
    "execution/db-bootstrapper",
    "execution/executor",
    "execution/executor-benchmark",
    "execution/executor-test-helpers",
    "execution/executor-types",
    "mempool",
    "network",
    "network/builder",
    "network/discovery",
    "network/memsocket",
    "network/netcore",
    "network/peer-monitoring-service/client",
    "network/peer-monitoring-service/server",
    "network/peer-monitoring-service/types",
    "sdk",
    "sdk/transaction-builder",
    "secure/net",
    "secure/push-metrics",
    "secure/storage",
    "secure/storage/github",
    "secure/storage/vault",
    "sf-stream",
    "state-sync/aptos-data-client",
    "state-sync/inter-component/consensus-notifications",
    "state-sync/inter-component/event-notifications",
    "state-sync/inter-component/mempool-notifications",
    "state-sync/state-sync-v2/data-streaming-service",
    "state-sync/state-sync-v2/state-sync-driver",
    "state-sync/state-sync-v2/state-sync-runtimes",
    "state-sync/storage-service/client",
    "state-sync/storage-service/server",
    "state-sync/storage-service/types",
    "storage/accumulator",
    "storage/aptosdb",
    "storage/backup/backup-cli",
    "storage/backup/backup-service",
    "storage/indexer",
    "storage/jellyfish-merkle",
    "storage/schemadb",
    "storage/scratchpad",
    "storage/state-view",
    "storage/storage-interface",
    "testsuite/aptos-fuzzer",
    "testsuite/aptos-fuzzer/fuzz",
    "testsuite/forge",
    "testsuite/forge-cli",
    "testsuite/generate-format",
    "testsuite/smoke-test",
    "testsuite/testcases",
    "types",
    "vm-validator",
]

# NOTE: default-members is the complete list of binaries that form the "production Aptos codebase". These members should
# never include crates that require fuzzing features or test features. These are the crates we want built with no extra
# test-only code included.
#
# For more, see the "Conditional compilation for tests" section in documentation/coding_guidelines.md.
default-members = [
    "aptos-move/genesis-viewer",
    "aptos-move/transaction-replay",
    "aptos-node",
    "config/management/operational",
    "config/seed-peer-generator",
    "consensus/safety-rules",
    "crates/aptos",
    "crates/aptos-faucet",
    "crates/aptos-keygen",
    "crates/aptos-rate-limiter",
    "crates/aptos-rosetta",
    "crates/transaction-emitter",
    "aptos-move/framework",
    "execution/db-bootstrapper",
    "storage/backup/backup-cli",
    "ecosystem/indexer",
    "ecosystem/node-checker",
]

[profile.release]
debug = true
overflow-checks = true

[profile.cli]
inherits = "release"
debug = false
opt-level = "z"
lto = true
strip = true
codegen-units = 1

[profile.bench]
debug = true

# This is a temporary workaround to avoid multiple library
# definitions for LZ4 (caused by rust-rocksdb).
# This will be removed once our pull requests land.
# https://github.com/rust-rocksdb/rust-rocksdb/issues/666
[patch.crates-io]
lz4 = { git = 'https://github.com/aptos-labs/lz4-rs' }
rocksdb = { git = 'https://github.com/aptos-labs/rust-rocksdb' }
serde-reflection = { git = "https://github.com/aptos-labs/serde-reflection", rev = "839aed62a20ddccf043c08961cfe74875741ccba" }
