[package]
name = "aptos-telemetry"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos telemetry utilities"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.3.21"
once_cell = "1.10.0"
prometheus = { version = "0.13.0", default-features = false }
rand = "0.7.3"
rand_core = "0.5.1"
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.137", features = ["derive"], default-features = false }
serde_json = "1.0.81"
sysinfo = "0.24.2"
tokio = { version = "1.18.2" }
tokio-stream = "0.1.8"
uuid = { version = "1.0.0", features = ["v4", "serde"] }

aptos-api = { path = "../../api" }
aptos-config = { path = "../../config" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-mempool = { path = "../../mempool" }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }

aptosdb = { path = "../../storage/aptosdb" }
consensus = { path = "../../consensus" }
network = { path = "../../network" }
state-sync-driver = { path = "../../state-sync/state-sync-v2/state-sync-driver" }
