[package]
name = "aptos-telemetry-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.8"
hex = "0.4.3"
jsonwebtoken = "8.1"
tokio = { version = "1.18.2", features = ["full"] }
warp = { version = "0.3.2", features = ["tls"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.24"
serde_repr = "0.1"
thiserror = "1.0"
chrono = "0.4"
bcs = "0.1.3"
tokio_schedule = "0.3.0"
reqwest = { version = "0.11.10", features = ["json"] }
rand = "0.7.3"
rand_core = { version = "0.5.1", default-features = false }
url = "2.2.2"
anyhow = "1.0.57"

aptos-types = { path = "../../types" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-crypto-derive = { path = "../../crates/aptos-crypto-derive" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-config = { path = "../../config" }
aptos-infallible = { path = "../../crates/aptos-infallible" }

